SoftUniBazar/Controllers/AdController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SoftUniBazar.Data;
using SoftUniBazar.Data.Constants;
using SoftUniBazar.Data.Models;
using SoftUniBazar.Models;
using System.Security.Claims;

namespace SoftUniBazar.Controllers
{
    [Authorize]
    public class AdController : Controller
    {
        private readonly BazarDbContext _context;

        public AdController(BazarDbContext context)
        {
            _context = context;
        }

        [HttpGet]
        public async Task<IActionResult> All()
        {
            var model = await _context.Ads
                .AsNoTracking()
                .Select(x => new AdInfoViewModel()
                {
                    Id = x.Id,
                    Name = x.Name,
                    Description = x.Description,
                    ImageUrl = x.ImageUrl,
                    CreatedOn = x.CreatedOn.ToString(DataConstants.DateFormat),
                    Category = x.Category.Name,
                    Price = $"{x.Price:F2}",
                    Owner = x.Owner.UserName
                })
                .ToListAsync();

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Add()
        {
            var model = new AdFormAddViewModel
            {
                Categories = await GetCategoriesAsync()
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Add(AdFormAddViewModel model)
        {
            if (!ModelState.IsValid)
            {
                model.Categories = await GetCategoriesAsync();
                return View(model);
            }

            var entity = new Ad()
            {
                Name = model.Name,
                Description = model.Description,
                ImageUrl = model.ImageUrl,
                CategoryId = model.CategoryId,
                OwnerId = GetUserId(),
                Price = model.Price,
                CreatedOn = DateTime.Now,
            };

            await _context.Ads.AddAsync(entity);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(All));
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var model = await GetAdByIdAsync(id);

            if (model == null)
            {
                return NotFound();
            }

            if (model.OwnerId != GetUserId())
            {
                return Unauthorized();
            }

            var viewModel = new AdEditFormViewModel()
            {
                Id = model.Id,
                Name = model.Name,
                Description = model.Description,
                ImageUrl = model.ImageUrl,
                CategoryId = model.CategoryId,
                Price = model.Price,
                Categories = await GetCategoriesAsync()
            };

            return View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, AdEditFormViewModel viewModel)
        {
            if (id != viewModel.Id)
            {
                return BadRequest();
            }

            var model = await GetAdByIdAsync(id);

            if (model == null)
            {
                return NotFound();
            }

            if (model.OwnerId != GetUserId())
            {
                return Unauthorized();
            }

            if (!ModelState.IsValid)
            {
                viewModel.Categories = await GetCategoriesAsync();
                return View(viewModel);
            }

            model.Name = viewModel.Name;
            model.Description = viewModel.Description;
            model.ImageUrl = viewModel.ImageUrl;
            model.Price = viewModel.Price;
            model.CategoryId = viewModel.CategoryId;

            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(All));
        }

        [HttpPost]
        public async Task<IActionResult> AddToCart(int id)
        {
            var model = await GetAdByIdAsync(id);

            if (model == null)
            {
                return NotFound();
            }

            if (!await _context.AdsBuyers.AnyAsync(x => x.BuyerId == GetUserId() && x.AdId == id))
            {
                await _context.AdsBuyers.AddAsync(new AdBuyer()
                {
                    BuyerId = GetUserId(),
                    AdId = id
                });

                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Cart));
            }
            return RedirectToAction(nameof(All));
        }

        [HttpPost]
        public async Task<IActionResult> RemoveFromCart(int id)
        {
            var model = await _context.AdsBuyers
                .FirstOrDefaultAsync(x => x.BuyerId == GetUserId() && x.AdId == id);

            if (model == null)
            {
                return NotFound();
            }

            _context.AdsBuyers.Remove(model);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(All));
        }

        [HttpGet]
        public async Task<IActionResult> Cart()
        {
            var model = await _context.AdsBuyers
                .AsNoTracking()
                .Where(x => x.BuyerId == GetUserId())
                .Select(x => new AdInfoViewModel()
                {
                    Id = x.Ad.Id,
                    Name = x.Ad.Name,
                    Description = x.Ad.Description,
                    ImageUrl = x.Ad.ImageUrl,
                    CreatedOn = x.Ad.CreatedOn.ToString(DataConstants.DateFormat),
                    Category = x.Ad.Category.Name,
                    Price = $"{x.Ad.Price:F2}",
                    Owner = x.Ad.Owner.UserName
                })
                .ToListAsync();

            return View(model);
        }


        private async Task<Ad?> GetAdByIdAsync(int id)
        {
            return await _context.Ads
                .FirstOrDefaultAsync(x => x.Id == id);
        }

        private string GetUserId()
        {
            return User.FindFirstValue(ClaimTypes.NameIdentifier) ?? string.Empty;
        }

        private async Task<ICollection<CategoryInfoViewModel>> GetCategoriesAsync()
        {
            return await _context.Categories
                .AsNoTracking()
                .Select(x => new CategoryInfoViewModel()
                {
                    Id = x.Id,
                    Name = x.Name,
                })
                .ToListAsync();
        }
    }
}

SoftUniBazar/Views/Ad/Add.cshtml
@model AdFormAddViewModel
@{
    ViewBag.Title = "Create a New Ad";
}

<h2 class="text-center">@ViewBag.Title</h2>
<hr />

<div class="row">
    <div class="col-sm-12 offset-lg-2 col-lg-8 offset-xl-3 col-xl-6">
        <form asp-action="Add" method="post">
            <div class="mb-3">
                <label asp-for="@Model.Name" class="form-label-add-edit">Name</label>
                <input asp-for="@Model.Name" class="form-control" aria-required="true" />
                <span asp-validation-for="@Model.Name" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="@Model.Description" class="form-label-add-edit">Description</label>
                <textarea asp-for="@Model.Description" class="form-control" aria-required="true" rows="5"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="@Model.ImageUrl" class="form-label-add-edit">Image URL</label>
                <input asp-for="@Model.ImageUrl" class="form-control" aria-required="true" />
                <span asp-validation-for="@Model.ImageUrl" class="text-danger"></span>
            </div>
             <div class="mb-3">
                <label asp-for="@Model.Price" class="form-label-add-edit">Price</label>
                <input asp-for="@Model.Price" class="form-control" aria-required="true" rows="5" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="@Model.CategoryId" class="form-label-add-edit">Category</label>
                <select asp-for="@Model.CategoryId" class="form-control" aria-required="true">
                    @foreach (var type in Model.Categories)
                    {
                        <option value="@type.Id">@type.Name</option>
                    }
                </select>
                <span asp-validation-for="@Model.CategoryId" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <input class="btn btn-warning mb-2 w-100 p-3 fw-bold" type="submit" value="Add" />
            </div>
        </form>
    </div>
</div>


@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

SoftUniBazar/Views/Ad/All.cshtml
@model IEnumerable<AdInfoViewModel>
@{
    ViewBag.Title = "Selected Ads for You";
}


<h2 class="text-center">@ViewBag.Title</h2>
<hr />

<div class="text-center row">
    @foreach (var a in Model)
    {
        <div class="card col-4" style="width: 20rem; ">
            <div class="card-body">
                <h5 class="card-title mt-1">@a.Name</h5>
                <img class="card-img-top" src=@a.ImageUrl alt="Ad Image">
                <p class="mb-0"><span class="fw-bold">Added on: </span>@a.CreatedOn</p>
                <p class="mb-0"><span class="fw-bold">Category: </span>@a.Category</p>
                <p class="mb-0"><span class="fw-bold">Description: </span>@a.Description</p>
                <p class="mb-0"><span class="fw-bold">Price: </span>@a.Price BGN</p>
                <p class="mb-0"><span class="fw-bold">Seller: </span>@a.Owner</p>
            </div>

            @if (User.Identity.Name == a.Owner)
            {
                <a asp-controller="Ad" asp-action="Edit" asp-route-id="@a.Id" class="btn btn-warning mb-2 w-100 p-3 fw-bold">Edit the Ad</a>
            }
            else
            {
                <form class="input-group-sm " asp-controller="Ad" asp-action="AddToCart" asp-route-id="@a.Id">
                    <input type="submit" value="Add to Cart" class="fs-6 btn btn-warning mb-3 w-100 p-3 fw-bold" />
                </form>
            }
        </div>
    }
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

SoftUniBazar/Views/Ad/Cart.cshtml
@model IEnumerable<AdInfoViewModel>
@{
    ViewBag.Title = "My Cart";
}


<h2 class="text-center">@ViewBag.Title</h2>
<hr />

<div class="text-center row">
    @foreach (var a in Model)
    {
        <div class="card col-4" style="width: 20rem; ">
            <div class="card-body">
                <h5 class="card-title mt-1">@a.Name</h5>
                <img class="card-img-top" src=@a.ImageUrl alt="Ad Image">
                <p class="mb-0"><span class="fw-bold">Added on: </span>@a.CreatedOn</p>
                <p class="mb-0"><span class="fw-bold">Category: </span>@a.Category</p>
                <p class="mb-0"><span class="fw-bold">Description: </span>@a.Description</p>
                <p class="mb-0"><span class="fw-bold">Price: </span>@a.Price BGN</p>
                <p class="mb-0"><span class="fw-bold">Seller: </span>@a.Owner</p>
            </div>

            @if (User.Identity.Name != a.Owner)
            {
                <form class="input-group-sm " asp-controller="Ad" asp-action="RemoveFromCart" asp-route-id="@a.Id">
                    <input type="submit" value="Remove from Cart" class="fs-6 btn btn-warning mb-3 w-100 p-3 fw-bold" />
                </form>
            }
        </div>
    }
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

SoftUniBazar/Views/Ad/Edit.cshtml
@model AdEditFormViewModel
@{
    ViewBag.Title = "Edit an Ad";
}

<h2 class="text-center">@ViewBag.Title</h2>
<hr />

<div class="row">
    <div class="col-sm-12 offset-lg-2 col-lg-8 offset-xl-3 col-xl-6">
        <form asp-action="Edit" method="post">
            <div class="mb-3">
                <label asp-for="@Model.Name" class="form-label-add-edit">Name</label>
                <input asp-for="@Model.Name" class="form-control" aria-required="true" />
                <span asp-validation-for="@Model.Name" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="@Model.Description" class="form-label-add-edit">Description</label>
                <textarea asp-for="@Model.Description" class="form-control" aria-required="true" rows="5"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="@Model.ImageUrl" class="form-label-add-edit">Image URL</label>
                <input asp-for="@Model.ImageUrl" class="form-control" aria-required="true" />
                <span asp-validation-for="@Model.ImageUrl" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="@Model.Price" class="form-label-add-edit">Price</label>
                <input asp-for="@Model.Price" class="form-control" aria-required="true" rows="5" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="@Model.CategoryId" class="form-label-add-edit">Category</label>
                <select asp-for="@Model.CategoryId" class="form-control" aria-required="true">
                    @foreach (var type in Model.Categories)
                    {
                        <option value="@type.Id">@type.Name</option>
                    }
                </select>
                <span asp-validation-for="@Model.CategoryId" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <input class="btn btn-warning mb-2 w-100 p-3 fw-bold" type="submit" value="Edit" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}